image: hipay/gitlab-ci-base:jessie

stages:
  - package

package:
 stage: package
 before_script:
    - apt-get update
    - apt-get install -y zip php5 libapache2-mod-php5
 script:
    - echo " Package module $CI_COMMIT_REF_SLUG"
    - rm -Rf ./vendor && composer install &&  sh ./bin/deployment/packaging.sh
    - mkdir $CI_COMMIT_REF_SLUG
    - mkdir $CI_COMMIT_REF_SLUG/package
    - cp ./dist/*.tgz $CI_COMMIT_REF_SLUG/package/Allopass_Hipay-${CI_COMMIT_REF_SLUG}.tgz
    - ./bin/deployment/deploy_project.sh
 tags:
    - pi-commerce-no-overlay
 artifacts:
  paths:
    - ./dist
